"""
Email Service
-------------
Sends HTML interview invitation emails via SMTP (Resend / any STARTTLS provider).
Falls back to logging the deep link if SMTP_USER or SMTP_PASS is not configured.
"""
from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from core.config import settings

logger = logging.getLogger(__name__)

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: Arial, sans-serif; background: #f4f4f4; padding: 20px; }}
    .card {{ background: white; border-radius: 8px; padding: 32px; max-width: 560px; margin: auto; }}
    h2 {{ color: #1a1a2e; }}
    p {{ color: #444; line-height: 1.6; }}
    .btn {{
      display: inline-block; margin-top: 24px; padding: 14px 28px;
      background: #6c47ff; color: white; border-radius: 6px;
      text-decoration: none; font-weight: bold; font-size: 16px;
    }}
    .footer {{ margin-top: 32px; color: #999; font-size: 12px; }}
  </style>
</head>
<body>
  <div class="card">
    <h2>You have been invited to interview!</h2>
    <p>Hi <strong>{candidate_name}</strong>,</p>
    <p>
      Congratulations! You have been shortlisted for the
      <strong>{job_title}</strong> position.
    </p>
    <p>
      Please complete your async video interview at your convenience.
      You can open it in your web browser or in the HireFlow mobile app:
    </p>
    <a class="btn" href="{web_link}">Start in Web Browser</a>
    <p style="margin-top:16px;">
      <a href="{deep_link}" style="color: #6c47ff;">Open in Mobile App</a>
    </p>
    <div class="footer">
      This invitation was generated by HireFlow. If you believe this is a
      mistake, please ignore this email.
    </div>
  </div>
</body>
</html>
"""


def send_invite_email(
    to_email: str,
    candidate_name: str,
    job_title: str,
    interview_token: str,
) -> bool:
    """
    Send an interview invitation email with the deep link embedded.

    Returns True if the email was sent (or logged), False on hard failure.
    """
    deep_link = f"hireflow://interview/{interview_token}"
    web_link = f"{settings.FRONTEND_URL}/interview/{interview_token}"

    # --- Fallback: log if SMTP not configured ---
    if not settings.SMTP_USER or not settings.SMTP_PASS:
        logger.info(
            f"[EMAIL MOCK] To: {to_email} | Candidate: {candidate_name} | "
            f"Job: {job_title} | Web link: {web_link} | Deep link: {deep_link}"
        )
        return True

    # --- Real SMTP send via Resend (or any provider) ---
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"HireFlow Interview Invitation: {job_title}"
        msg["From"] = settings.SMTP_FROM_EMAIL
        msg["To"] = to_email

        html_body = _HTML_TEMPLATE.format(
            candidate_name=candidate_name,
            job_title=job_title,
            deep_link=deep_link,
            web_link=web_link,
        )
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASS)
            server.sendmail(settings.SMTP_FROM_EMAIL, to_email, msg.as_string())

        logger.info(f"Interview invitation sent to {to_email} for '{job_title}'")
        return True

    except Exception as exc:
        logger.error(f"Failed to send email to {to_email}: {exc}")
        return False
