"""
Email Service
-------------
Sends HTML interview invitation emails.

Two paths, tried in this order:
  1. Resend's HTTP API (RESEND_API_KEY set) — a single POST, no SMTP
     handshake, no port-blocking concerns on Railway. This is the
     recommended path.
  2. SMTP (SMTP_USER / SMTP_PASS set) — works with Resend's SMTP relay too
     (smtp.resend.com, user "resend", pass = your Resend API key) or any
     other STARTTLS provider.
Falls back to logging the deep link if neither is configured.
"""
from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import httpx

from core.config import settings

logger = logging.getLogger(__name__)

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: 'Inter', Arial, sans-serif; background: #f9f9ff; padding: 40px 20px; color: #151c27; }}
    .card {{ background: #ffffff; border-radius: 24px; padding: 40px; max-width: 560px; margin: auto; box-shadow: 0 4px 20px rgba(0, 0, 0, 0.04); border: 1px solid #dce2f3; text-align: center; }}
    .logo {{ font-size: 24px; font-weight: 800; color: #000000; margin-bottom: 24px; letter-spacing: -0.02em; }}
    h2 {{ color: #000000; font-size: 28px; font-weight: 800; margin-bottom: 16px; letter-spacing: -0.01em; }}
    p {{ color: #45474a; line-height: 1.6; font-size: 16px; margin-bottom: 24px; }}
    .btn {{
      display: inline-block; padding: 16px 32px;
      background: #fc8a40; color: #672c00; border-radius: 16px;
      text-decoration: none; font-weight: 600; font-size: 16px;
      box-shadow: 0 4px 20px rgba(252, 138, 64, 0.3);
    }}
    .mobile-link {{ display: inline-block; margin-top: 24px; color: #000000; text-decoration: underline; font-weight: 500; }}
    .footer {{ margin-top: 40px; color: #76777b; font-size: 12px; border-top: 1px solid #dce2f3; padding-top: 24px; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="logo">HireFlow</div>
    <h2>You have been invited to interview!</h2>
    <p>Hi <strong>{candidate_name}</strong>,</p>
    <p>
      Congratulations! You have been shortlisted for the
      <strong>{job_title}</strong> position.
    </p>
    <p>
      Please complete your async video interview at your convenience.
      You can open it in your web browser or in the HireFlow mobile app.
    </p>
    <a class="btn" href="{web_link}">Start in Web Browser</a>
    <br>
    <a class="mobile-link" href="{deep_link}">Open in Mobile App</a>
    <br>
    <a class="mobile-link" href="{apk_link}" style="margin-top: 12px; font-size: 14px; color: #45474a;">Download Mobile App (.apk)</a>
    <div class="footer">
      This invitation was generated by HireFlow. If you believe this is a
      mistake, please ignore this email.
    </div>
  </div>
</body>
</html>
"""


def send_invite_email(
    to_email: str,
    candidate_name: str,
    job_title: str,
    interview_token: str,
) -> bool:
    """
    Send an interview invitation email with the deep link embedded.

    Returns True if the email was sent (or logged), False on hard failure.
    """
    deep_link = f"hireflow://interview/{interview_token}"
    web_link = f"{settings.FRONTEND_URL}/interview/{interview_token}"
    apk_link = f"{settings.FRONTEND_URL}/downloads/hireflow.apk"
    html_body = _HTML_TEMPLATE.format(
        candidate_name=candidate_name,
        job_title=job_title,
        deep_link=deep_link,
        web_link=web_link,
        apk_link=apk_link,
    )
    subject = f"HireFlow Interview Invitation: {job_title}"

    # --- Path 1: Resend HTTP API (preferred — no SMTP port issues) ---
    if settings.RESEND_API_KEY:
        # Resend Sandbox restricts sending to your verified email address
        actual_to_email = to_email
        if "onboarding@resend.dev" in settings.SMTP_FROM_EMAIL:
            actual_to_email = "koushal.sub@gmail.com"
            logger.info(f"Overriding destination {to_email} -> {actual_to_email} due to Resend sandbox restrictions.")

        try:
            resp = httpx.post(
                "https://api.resend.com/emails",
                headers={"Authorization": f"Bearer {settings.RESEND_API_KEY}"},
                json={
                    "from": settings.SMTP_FROM_EMAIL,
                    "to": [actual_to_email],
                    "subject": subject,
                    "html": html_body,
                },
                timeout=10,
            )
            if resp.status_code in (200, 201):
                logger.info(f"Interview invitation sent via Resend API to {to_email} for '{job_title}'")
                return True
            logger.error(f"Resend API send failed ({resp.status_code}): {resp.text}")
            # fall through to SMTP / mock below if SMTP is also configured
        except Exception as exc:
            logger.error(f"Resend API request failed: {exc}")
            # fall through

    # --- Fallback: log if neither Resend API nor SMTP is configured ---
    if not settings.RESEND_API_KEY and (not settings.SMTP_USER or not settings.SMTP_PASS):
        logger.info(
            f"[EMAIL MOCK] To: {to_email} | Candidate: {candidate_name} | "
            f"Job: {job_title} | Web link: {web_link} | Deep link: {deep_link}"
        )
        return True

    if not settings.SMTP_USER or not settings.SMTP_PASS:
        # Resend API was configured but failed, and there's no SMTP fallback.
        return False

    # --- Path 2: SMTP (Resend's SMTP relay or any STARTTLS provider) ---
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = settings.SMTP_FROM_EMAIL
        msg["To"] = to_email
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASS)
            server.sendmail(settings.SMTP_FROM_EMAIL, to_email, msg.as_string())

        logger.info(f"Interview invitation sent via SMTP to {to_email} for '{job_title}'")
        return True

    except Exception as exc:
        logger.error(f"Failed to send email to {to_email}: {exc}")
        return False
