/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e2e8f8",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#7073ff",
        "surface-container-low": "#f0f3ff",
        "surface-variant": "#dce2f3",
        "on-secondary-fixed-variant": "#763300",
        "primary": "#000000",
        "on-secondary-container": "#672c00",
        "primary-fixed": "#e2e2e6",
        "on-secondary-fixed": "#331200",
        "surface-dim": "#d3daea",
        "inverse-primary": "#c6c6ca",
        "error-container": "#ffdad6",
        "secondary": "#9b4500",
        "on-background": "#151c27",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-bright": "#f9f9ff",
        "surface-container": "#e7eefe",
        "on-primary-fixed": "#1a1c1f",
        "tertiary-fixed": "#e1e0ff",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#ebf1ff",
        "primary-fixed-dim": "#c6c6ca",
        "on-primary-fixed-variant": "#45474a",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-container": "#fc8a40",
        "inverse-surface": "#2a313d",
        "secondary-fixed": "#ffdbc9",
        "on-tertiary-fixed": "#07006c",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#07006c",
        "background": "#f9f9ff",
        "surface": "#f9f9ff",
        "primary-container": "#1a1c1f",
        "on-surface-variant": "#45474a",
        "on-primary-container": "#838487",
        "outline-variant": "#c6c6ca",
        "secondary-fixed-dim": "#ffb68d",
        "on-tertiary": "#ffffff",
        "tertiary": "#000000",
        "outline": "#76777b",
        "surface-container-highest": "#dce2f3",
        "on-error-container": "#93000a",
        "on-surface": "#151c27",
        "surface-tint": "#5d5e62",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        "gutter": "24px",
        "unit": "8px",
        "container-max": "1280px",
        // Legacy aliases kept for backward compat
        "stack-md": "32px",
        "margin-page": "80px",
        "stack-lg": "64px",
        "stack-xl": "120px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.1", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        // Legacy aliases
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "500" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
